In [14]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [15]:
A = np.random.randn(100)

In [16]:
A

array([-0.33805124,  0.71439775,  0.47377695,  0.85062188,  0.40557884,
       -0.12858051, -0.76704054, -1.7279282 , -0.72619593,  0.01704433,
       -0.35623474,  0.13002658, -1.39325219, -2.34513373,  1.07528027,
        0.63072084,  0.45309892,  0.06777757,  1.53505322,  0.65282184,
        1.0343717 , -0.16025411,  0.47939386,  1.33720744,  0.62900882,
        0.07969853, -1.85964021, -0.81110191, -0.08346885,  0.6348737 ,
        0.8297596 , -1.42338847,  0.3123679 , -0.76763164,  0.88203264,
       -0.96584841,  0.38139692, -1.08651604,  0.16727065,  0.26547415,
       -2.22083163, -0.66968072,  0.55598534, -0.70949068, -1.02020144,
        1.3929304 ,  0.27348732, -0.08442314,  0.04416419, -0.11822509,
       -0.61354516,  0.55626536,  1.02830611,  0.46079467, -0.058348  ,
        0.87601812, -1.29052021, -0.20657578, -0.96976076,  0.66517828,
        0.60016332,  0.11651683,  1.21955299, -1.13467658,  0.21992279,
       -1.59608302,  0.0110478 , -1.6936947 , -1.16381166, -0.43

In [17]:
A = 10*A +50

In [18]:
A

array([ 46.61948761,  57.14397749,  54.73776951,  58.50621879,
        54.0557884 ,  48.71419489,  42.32959459,  32.72071796,
        42.73804071,  50.1704433 ,  46.43765265,  51.30026575,
        36.06747809,  26.54866267,  60.75280273,  56.30720836,
        54.53098919,  50.67777568,  65.35053222,  56.52821845,
        60.34371697,  48.39745885,  54.7939386 ,  63.37207441,
        56.29008821,  50.79698527,  31.40359788,  41.88898086,
        49.16531149,  56.34873705,  58.29759597,  35.76611529,
        53.12367903,  42.32368356,  58.82032645,  40.34151589,
        53.81396923,  39.13483958,  51.67270652,  52.65474151,
        27.79168373,  43.30319281,  55.55985339,  42.90509322,
        39.79798558,  63.92930404,  52.73487318,  49.15576855,
        50.44164189,  48.81774907,  43.86454839,  55.56265363,
        60.28306107,  54.60794667,  49.41652001,  58.76018116,
        37.09479793,  47.93424215,  40.30239243,  56.65178277,
        56.00163315,  51.16516828,  62.19552992,  38.65

In [19]:
#設定為5*20的向量矩陣
A.shape = (5, 20)
A

array([[ 46.61948761,  57.14397749,  54.73776951,  58.50621879,
         54.0557884 ,  48.71419489,  42.32959459,  32.72071796,
         42.73804071,  50.1704433 ,  46.43765265,  51.30026575,
         36.06747809,  26.54866267,  60.75280273,  56.30720836,
         54.53098919,  50.67777568,  65.35053222,  56.52821845],
       [ 60.34371697,  48.39745885,  54.7939386 ,  63.37207441,
         56.29008821,  50.79698527,  31.40359788,  41.88898086,
         49.16531149,  56.34873705,  58.29759597,  35.76611529,
         53.12367903,  42.32368356,  58.82032645,  40.34151589,
         53.81396923,  39.13483958,  51.67270652,  52.65474151],
       [ 27.79168373,  43.30319281,  55.55985339,  42.90509322,
         39.79798558,  63.92930404,  52.73487318,  49.15576855,
         50.44164189,  48.81774907,  43.86454839,  55.56265363,
         60.28306107,  54.60794667,  49.41652001,  58.76018116,
         37.09479793,  47.93424215,  40.30239243,  56.65178277],
       [ 56.00163315,  51.16516828,  

In [20]:
#改成100個矩陣,但reshape則是額外新增的array並沒有改變原本的A陣列
A.reshape(100,1)

array([[ 46.61948761],
       [ 57.14397749],
       [ 54.73776951],
       [ 58.50621879],
       [ 54.0557884 ],
       [ 48.71419489],
       [ 42.32959459],
       [ 32.72071796],
       [ 42.73804071],
       [ 50.1704433 ],
       [ 46.43765265],
       [ 51.30026575],
       [ 36.06747809],
       [ 26.54866267],
       [ 60.75280273],
       [ 56.30720836],
       [ 54.53098919],
       [ 50.67777568],
       [ 65.35053222],
       [ 56.52821845],
       [ 60.34371697],
       [ 48.39745885],
       [ 54.7939386 ],
       [ 63.37207441],
       [ 56.29008821],
       [ 50.79698527],
       [ 31.40359788],
       [ 41.88898086],
       [ 49.16531149],
       [ 56.34873705],
       [ 58.29759597],
       [ 35.76611529],
       [ 53.12367903],
       [ 42.32368356],
       [ 58.82032645],
       [ 40.34151589],
       [ 53.81396923],
       [ 39.13483958],
       [ 51.67270652],
       [ 52.65474151],
       [ 27.79168373],
       [ 43.30319281],
       [ 55.55985339],
       [ 42

In [21]:
#修改A陣列為100*1
A = A.reshape(100,1)
A

array([[ 46.61948761],
       [ 57.14397749],
       [ 54.73776951],
       [ 58.50621879],
       [ 54.0557884 ],
       [ 48.71419489],
       [ 42.32959459],
       [ 32.72071796],
       [ 42.73804071],
       [ 50.1704433 ],
       [ 46.43765265],
       [ 51.30026575],
       [ 36.06747809],
       [ 26.54866267],
       [ 60.75280273],
       [ 56.30720836],
       [ 54.53098919],
       [ 50.67777568],
       [ 65.35053222],
       [ 56.52821845],
       [ 60.34371697],
       [ 48.39745885],
       [ 54.7939386 ],
       [ 63.37207441],
       [ 56.29008821],
       [ 50.79698527],
       [ 31.40359788],
       [ 41.88898086],
       [ 49.16531149],
       [ 56.34873705],
       [ 58.29759597],
       [ 35.76611529],
       [ 53.12367903],
       [ 42.32368356],
       [ 58.82032645],
       [ 40.34151589],
       [ 53.81396923],
       [ 39.13483958],
       [ 51.67270652],
       [ 52.65474151],
       [ 27.79168373],
       [ 43.30319281],
       [ 55.55985339],
       [ 42