##### 第一題：
##### 題目：給定一個矩陣m，裡面的值都大於0。
##### 請將矩陣m裡大於等於1的數字都變成1，小於1的變成0。
 
##### m = np.array([[0,1,10],[2,6,7]])
 
##### 提示：使用巢狀迴圈(nested loop)加判斷式

In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [24]:
m = np.array([[0, 1, 10],[2, 6, 7]])
for x in m[m>=1]:
    m[m>=1] = 1
    for y in m[m<1]:
        m[m<1] = 0
m

array([[0, 1, 1],
       [1, 1, 1]])

In [47]:
randm = np.random.randint(-100, 100, (2,3))
print(randm)
for x in randm[randm>=1]:
    randm[randm>=1] = 1
    for y in randm[randm<1]:
        randm[randm<1] = 0
randm

[[-59  66 -79]
 [ 10 -59  70]]


array([[0, 1, 0],
       [1, 0, 1]])

##### 第二題：
##### 有A,B,C三個班級，每班皆有10個學生，
##### 期中考結束後，老師希望計算各班級每位學生的加權平均成績。 
##### 請隨機產生3個班級的成績單,每班10人,共五科,
##### 權重為weights=[0.25,0.25,0.25,0.15,0.10]。
##### 請算出班級加權平均成績，並以一個array輸出。

In [96]:
grades = np.random.randint(0, 100, 3*5*10)
weights = np.array([0.25,0.25,0.25,0.15,0.10])
print(grades)
reshape_grades  = grades.reshape(3,10,5)
g = reshape_grades * weights
g

[97  1  4 65  4 13 96 26 96 19 43  2 50 12 42 11 14 34 74 89 47  3 59 57 27
  1 78 17 56 77 48 60  0 34 20 35  0 89 55 14 81 83 48 83 13 31 18  5 72 73
 31 68 53 94 61 32 70 62 48 45 73  1 14 98 56  3 41 33 17 47 91  7 91 25 42
 33 20  3 59 27 67 34 39  7 64 63 92 69 39 88 51  1 35  9 19 35 35 92 26 54
 73 60  1  6 13 59 51  4 55 64 27 51 65 28 27 31 53 81 63 58 27  6 60 57 46
 55 91 57 43 46 92  0 21 72 49 10 97  4 41 26 34  3 76 38  6 95 40 56 90 17]


array([[[ 24.25,   0.25,   1.  ,   9.75,   0.4 ],
        [  3.25,  24.  ,   6.5 ,  14.4 ,   1.9 ],
        [ 10.75,   0.5 ,  12.5 ,   1.8 ,   4.2 ],
        [  2.75,   3.5 ,   8.5 ,  11.1 ,   8.9 ],
        [ 11.75,   0.75,  14.75,   8.55,   2.7 ],
        [  0.25,  19.5 ,   4.25,   8.4 ,   7.7 ],
        [ 12.  ,  15.  ,   0.  ,   5.1 ,   2.  ],
        [  8.75,   0.  ,  22.25,   8.25,   1.4 ],
        [ 20.25,  20.75,  12.  ,  12.45,   1.3 ],
        [  7.75,   4.5 ,   1.25,  10.8 ,   7.3 ]],

       [[  7.75,  17.  ,  13.25,  14.1 ,   6.1 ],
        [  8.  ,  17.5 ,  15.5 ,   7.2 ,   4.5 ],
        [ 18.25,   0.25,   3.5 ,  14.7 ,   5.6 ],
        [  0.75,  10.25,   8.25,   2.55,   4.7 ],
        [ 22.75,   1.75,  22.75,   3.75,   4.2 ],
        [  8.25,   5.  ,   0.75,   8.85,   2.7 ],
        [ 16.75,   8.5 ,   9.75,   1.05,   6.4 ],
        [ 15.75,  23.  ,  17.25,   5.85,   8.8 ],
        [ 12.75,   0.25,   8.75,   1.35,   1.9 ],
        [  8.75,   8.75,  23.  ,   3.9 ,   5.4 ]

In [95]:
g[2][9][4],g[0][0][0]

(6.2000000000000002, 0.25)

In [106]:
AdvCal = np.random.randint(0, 100, 3*30*3)
weights_1 = np.array([0.2, 0.35, 0.45])
weights_2 = np.array([0 , 0.4, 0.6])
reshape_AdvCal  = AdvCal.reshape(3,30,3)
g_end1 = reshape_AdvCal * weights_1 

g_end2 = reshape_AdvCal * weights_2

g_end1_dot =  np.dot(g_end1, weights_1)

g_end2_dot =  np.dot(g_end2, weights_2)

g_end2_dot

array([[ 35.96,  36.  ,  30.32,  25.56,  23.6 ,  11.2 ,  17.84,  32.92,
         34.48,  21.48,  19.84,  13.44,  10.24,  31.68,  34.92,  32.64,
         17.84,  12.44,  23.36,  19.4 ,  24.56,  12.92,  30.56,  39.64,
         28.08,  41.28,  12.04,  40.96,  38.12,  12.12],
       [ 11.2 ,  37.36,  40.52,  14.2 ,  35.2 ,  24.2 ,  34.12,  13.92,
          6.36,   7.64,  16.16,  22.44,  20.68,  37.12,  10.12,  36.64,
         21.16,  19.96,   7.04,  21.6 ,  48.68,  18.88,  30.36,  18.92,
         15.96,  37.44,  21.84,  23.8 ,  39.36,  13.68],
       [ 13.  ,  34.44,  11.2 ,  34.64,  20.16,  34.12,  30.56,  22.52,
         28.16,  17.88,  29.04,   3.04,  23.76,   9.6 ,  20.88,  11.8 ,
         21.56,  13.92,  29.6 ,  40.96,  20.36,  38.44,  35.32,  30.96,
         13.76,  35.52,  35.6 ,  35.44,  31.6 ,  16.96]])